import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { ReactQueryProvider } from "../../components/ReactQueryProvider/ReactQueryProvider";
import { Navbar } from "../../components/Navbar/Navbar";
import { AuthProvider } from "../../context/AuthContext";
import { createClient } from "@/clients/supabase-server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <div className="min-h-screen bg-black text-gray-100 transition-opacity duration-700 pt-20">
              <Navbar user={data.user} />
              <div className="container mx-auto px-4 py-6">{children}</div>
            </div>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
